version: '3'

services:
  torch_server:
    build:
      context: ./
      dockerfile: ./torch_server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  app_simulator:
    build:
      context: ./
      dockerfile: ./app_simulator/Dockerfile
    ports:
      - "8501:8501"