version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    ports:
      - "8000:8000"
  sim:
    build:
      context: ./
      dockerfile: ./simulator/Dockerfile
    ports:
      - "8501:8501"